spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_database
    username: root
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    host: "smtp.gmail.com"
    port: 587
    username: ${LOGIN_SMTP_USERNAME}
    password: ${LOGIN_SMTP_PASSWORD}

logging:
  level:
#    root: DEBUG
    org.springframework.web: DEBUG
    org.apache.catalina.core: DEBUG